### ISSUE TITLE
Add request.Host into Request

### ISSUE THREAD

**Issue by s8sg** [openfaas-incubator/go-function-sdk#2]
Request.Host provides the `Host` in which the request was forwarded. Example:
```
myfunction:8080  // in swarm
myfunction.openfaas-fn:8080 // in k8s
```

 Same can be added in the Request structure:
```go
type Request struct {
	Body        []byte
	Header      http.Header
	QueryString string
	Method      string
        Host        string
}
```
It's useful for knowing the function name. There is alternative way as such using `HOSTNAME`, although providing Host works in different deployments. User need to parse the host based on the deployment in use.

**Comment by s8sg** [comment]
To parse the function name, one can use a simple regex as such 
```regex
^[^:.]+\s*
```
This matches all character till the first occurrence of `:` or `.`. As OpenFaaS function doesn't let user use either of these characters in function name, it will work well.

**Comment by pmundt** [comment]
We ended up needing to do this in order to extract the function name for OPA auth [here](https://github.com/adaptant-labs/openfaas-function-auth-opa). We also added this to our version of [go-function-sdk](https://github.com/adaptant-labs/go-function-sdk), and are using this in a template you can pull from [here](https://github.com/adaptant-labs/openfaas-golang-http-gomod-template).

We'll begin gradually opening up PRs for the relevant bits in the coming days.

**Comment by alexellis** [comment]
Thank you for using OpenFaaS. 

@pmundt did you try using `os.Getenv("HOSTNAME")` first?

Please propose all new changes with an issue and wait for clearance before working on them. 

You can also discuss your ideas with us on Slack.

**Comment by pmundt** [comment]
No, I didn't know about HOSTNAME, so if this is sufficient, we'll simply switch over to using that instead. Thanks for the tip!

As far as proposing new issues before working on them - I note that this issue was opened on the 29th of July with no feedback until we triggered a PR yesterday. I've similarly opened up other issues that have had no feedback for a month. While I can understand that you are busy and that these issues may not be a high priority for OpenFaaS, we have certain things we are aiming to accomplish and simply do not have the luxury of time to wait for these periods of time before proceeding with implementation. The downside of this is that we may end up implementing things we later have to throw away or change, as seems to be the case here, but this is a risk we can live with.

I did not realize there was a Slack community, so I have registered for this now as well - hopefully this will save us both some time with regards to future contributions!

**Comment by s8sg** [comment]
@alexellis If I remember correctly HOSTNAME doesn’t work across all environments. I had the similar problem while using in the FaaSFlow. I already mentioned that while creating the issue. Proving Host with request seems more neat, and accurate across environment. I agree on the point on having discussions before the PR but strongly oppose discussion on ideas on slack when there is already an open issue with it

**Comment by alexellis** [comment]
`/etc/hostname` should work on every environment, that's how node info works.

What environment are you thinking of that doesn't work?

I would also caution use of request.Host since this may be subject to change depending on how we proxy code or whether we use a service mesh.

**Comment by alexellis** [comment]
> we have certain things we are aiming to accomplish and simply do not have the luxury of time to wait for these periods of time before proceeding with implementation.

Open source contributions do need to follow the process, whether contributors feel they have the time to work with it or otherwise. I would strongly recommend whether you want to maintain your own patches for everything you need, vs. making a case for it in the upstream project. 

Feel free to contact sales@openfaas.com about a commercial support retainer for backlog prioritisation, priority support and help with architecture / non-recurring engineering work / features.

**Comment by pmundt** [comment]
@alexellis making the case for it upstream requires actual engagement from upstream. You didn't provide this in any reasonable fashion, full stop. If you want us to follow a process, that's fine. And indeed, we did. The process, however, should do something other than block endlessly until commercial pressure is applied to advance things forward. If that's the business model you want to pursue, best of luck to you.

We initially chose to work on OpenFaaS over OpenWhisk as it seemed more open source friendly and better aligned with the work we wanted to do. Perhaps it's time to reconsider that decision.

**Comment by s8sg** [comment]
@alexellis I agree on the point on using Proxy. But In docker swarm using Hostname doesn’t work. For Kubernetes its fine. Please check: https://github.com/s8sg/faas-flow/issues/68

**Comment by pmundt** [comment]
@s8sg is correct, `os.Getenv("HOSTNAME")` in Docker Swarm does not work, and simply gives us the container ID. I also tried explicitly reading from `/etc/hostname`, just in case this was an environment variable mapping issue, but received the same result.

```
diff --git a/opa-auth/handler.go b/opa-auth/handler.go
index 264e42e..d283506 100644
--- a/opa-auth/handler.go
+++ b/opa-auth/handler.go
@@ -61,6 +61,12 @@ func isAuthorized(req handler.Request) bool {
                return false
        }
 
+       etcHost, _ := ioutil.ReadFile("/etc/hostname")
+
+       println("host == ", host)
+       println("getenv == ", os.Getenv("HOSTNAME"))
+       println("etc == ", string(etcHost))
+
        authzRequestPayload := map[string]map[string]interface{}{
                "input": {
                        "function": host,
```

Produces:

```
$ docker logs 9b1eb
Forking - ./handler []
2019/10/16 16:25:36 Started logging stderr from function.
2019/10/16 16:25:36 Started logging stdout from function.
2019/10/16 16:25:36 OperationalMode: http
2019/10/16 16:25:36 Timeouts: read: 10s, write: 10s hard: 10s.
2019/10/16 16:25:36 Listening on port: 8080
2019/10/16 16:25:36 Writing lock-file to: /tmp/.lock
2019/10/16 16:25:36 Metrics listening on port: 8081
2019/10/16 16:25:38 stderr: host ==  opa-auth
2019/10/16 16:25:38 stderr: getenv ==  9b1eb175dfbd
2019/10/16 16:25:38 stderr: etc ==  9b1eb175dfbd
2019/10/16 16:25:38 stderr: 
2019/10/16 16:25:38 GET / - 200 OK - ContentLength: 17
...
```
For reference, dumping the totality of os.Environ() (in another run, so the container ID is different) gives us:

```
2019/10/16 16:46:08 stderr: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2019/10/16 16:46:08 stderr: HOSTNAME=30180a7070ff
2019/10/16 16:46:08 stderr: fprocess=./handler
2019/10/16 16:46:08 stderr: OPA_URL=http://opa:8181
2019/10/16 16:46:08 stderr: mode=http
2019/10/16 16:46:08 stderr: upstream_url=http://127.0.0.1:8082
2019/10/16 16:46:08 stderr: HOME=/home/app

```
@alexellis Any other suggestions?

**Comment by s8sg** [comment]
How about adding an extra header while forwarding the request from OpenFaaS gateway that identifies the function name. Like: ‘X-Function-Name’. This may solve the issue once for all templates.

**Comment by alexellis** [comment]
@pmundt I don't see how this issue being open from July has any bearing on the context?

> we have certain things we are aiming to accomplish and simply do not have the luxury of time to wait for these periods of time before proceeding with implementation.

^ This is what I am referring to regarding commercial support, if you "simply do not have the time to wait" for your changes to be merged, then you may benefit from extra help.

As far as I'm aware, @s8sg and yourself do not work at the same company and you turned up on this issue just a few days ago and have received immediate attention, followed by a swift merge.

**Comment by alexellis** [comment]
> The process, however, should do something other than block endlessly until commercial pressure is applied to advance things forward.

This is not in any way what I said to you. Let's replay the events and look at your scenario?

@s8sg raised an issue in July whilst he was an active member of the project team
@s8sg left to pursue faas-flow and forgot about his issue

...

You arrived only yesterday and asked for the issue to be merged
I engaged immediately and gave feedback
You made a demanding statement "simply do not have the luxury of time to wait for these periods of time before proceeding with implementation"
I reassured you that if you have critical business pressure, you can get hands-on help and prioritisation whenever you need it
Your PR was merged within 1 day

What am I missing?

**Comment by alexellis** [comment]
Please see: [Setting expectations, support and SLAs](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#setting-expectations-support-and-slas)
